USE [master]
GO

/****** Object:  Database [db_acesso]    Script Date: 07/11/2018 09:22:57 ******/
CREATE DATABASE [db_acesso]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_acesso', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_acesso.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'db_acesso_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\db_acesso_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [db_acesso] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_acesso].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_acesso] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_acesso] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_acesso] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_acesso] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_acesso] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_acesso] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_acesso] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_acesso] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_acesso] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_acesso] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_acesso] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_acesso] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_acesso] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_acesso] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_acesso] SET  DISABLE_BROKER 
GO

ALTER DATABASE [db_acesso] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_acesso] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_acesso] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_acesso] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_acesso] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_acesso] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [db_acesso] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_acesso] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [db_acesso] SET  MULTI_USER 
GO

ALTER DATABASE [db_acesso] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_acesso] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_acesso] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_acesso] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [db_acesso] SET  READ_WRITE 
GO

